apiVersion: apps/v1
kind: Deployment
metadata:
  name: fit-strike-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fit-strike-app
  template:
    metadata:
      labels:
        app: fit-strike-app
    spec:
      containers:
      - name: fit-strike-app
        image: lucascamilo2024/fit-strike-api:latest
        ports:
        - containerPort: 80 # ajuste conforme sua aplicação
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "prod"
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: AWS_SECRET_ACCESS_KEY
          - name: AWS_REGION
            value: "us-east-1"