apiVersion: apps/v1
kind: Deployment
metadata:
  name: fit-strike-app
spec:
  replicas: 0
  selector:
    matchLabels:
      app: fit-strike-app
  template:
    metadata:
      labels:
        app: fit-strike-app
    spec:
      containers:
      - name: fit-strike-app
        image: lucascamilo2024/fit-strike-api:latest
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "prod"
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: AWS_SECRET_ACCESS_KEY
          - name: AWS_REGION
            value: "us-east-1"
        readinessProbe:
          httpGet:
            path: /actuator/health   # ajuste para o endpoint de health da sua aplicação
            port: 8080
          initialDelaySeconds: 3     # tempo antes da primeira checagem
          periodSeconds: 2           # intervalo entre checagens
          failureThreshold: 5        # quantas falhas até considerar "not ready"
          timeoutSeconds: 2          # timeout de cada checagem